#!/usr/bin/env python
from pyPdf import PdfFileReader, PdfFileWriter
from os.path import basename
import sys

def nameof(path):
    """Returns file basename stripped of file extension."""
    base = basename(path)
    index = base.rfind('.')
    return base[:index] if index > 0 else base

def burst(input, output_dir):
    base = nameof(input)
    reader = PdfFileReader(file(input, 'rb'))
    i = 0
    while i < reader.getNumPages():
        writer = PdfFileWriter()
        writer.addPage(reader.getPage(i))
        path = '%s+%03d.pdf' % (base, i+1)
        outputStream = file(output_dir + path, 'wb')
        writer.write(outputStream)
        outputStream.close()
        i += 1

burst(sys.argv[1], sys.argv[2])
