#!/usr/bin/env python
from pyPdf import PdfFileWriter, PdfFileReader
import sys

def join(inputs, output):
    writer = PdfFileWriter()
    for input in inputs:
        inputStream = file(input, 'rb')
        reader = PdfFileReader(inputStream)
        i = 0
        while i < reader.getNumPages():
            writer.addPage(reader.getPage(i))
            i += 1
    outputStream = file(output, 'wb')
    writer.write(outputStream)

join(sys.argv[2:], sys.argv[1])
